eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demoservice
          uri: lb://demoservice
          predicates:
            - Path=/demo/**
          filters:
            - RewritePath=/demo/(?<path>.*), /$\{path}
